program Purchase;

uses
  Forms,
  Windows,
  main1 in 'source\main1.pas' {main},
  ulogin in 'source\ulogin.pas' {LOGIN},
  DM3 in 'source\DM3.pas' {DM2: TDataModule},
  OrderSpec1 in 'Source\OrderSpec1.pas' {OrderSpec},
  Quotation1 in 'Source\SN231\Quotation1.pas' {Quotation},
  Quotation_ZS1 in 'Source\SN231\Quotation_ZS1.pas' {Quotation_ZS},
  Quotation_CL1 in 'Source\SN231\Quotation_CL1.pas' {Quotation_CL},
  SuppNew1 in 'Source\SuppNew1.pas' {SuppNew},
  Quotation_Print1 in 'Source\SN231\Quotation_Print1.pas' {Quotation_Print},
  PurSize1 in 'Source\SN212\PurSize1.pas' {PurSize},
  PurNoSize1 in 'Source\SN211\PurNoSize1.pas' {PurNoSize},
  PurNoSize_ZS1 in 'Source\SN211\PurNoSize_ZS1.pas' {PurNoSize_ZS},
  PurNoSize_CL1 in 'Source\SN211\PurNoSize_CL1.pas' {PurNoSize_CL},
  PurNoSize_BJ1 in 'Source\SN211\PurNoSize_BJ1.pas' {PurNoSize_BJ},
  PurNoSize_Ord1 in 'Source\SN211\PurNoSize_Ord1.pas' {PurNoSize_Ord},
  PurNoSize_Print1 in 'Source\SN211\PurNoSize_Print1.pas' {PurNoSize_Print},
  PurSize_ZS1 in 'Source\SN212\PurSize_ZS1.pas' {PurSize_ZS},
  PurSize_CL1 in 'Source\SN212\PurSize_CL1.pas' {PurSize_CL},
  PurSize_Print1 in 'Source\SN212\PurSize_Print1.pas' {PurSize_Print},
  PurSize_Ord1 in 'Source\SN212\PurSize_Ord1.pas' {PurSize_Ord},
  PurSize_BJ1 in 'Source\SN212\PurSize_BJ1.pas' {PurSize_BJ},
  PurOther1 in 'Source\SN213\PurOther1.pas' {PurOther},
  PurOther_ZS1 in 'Source\SN213\PurOther_ZS1.pas' {PurOther_ZS},
  PurOther_CL1 in 'Source\SN213\PurOther_CL1.pas' {PurOther_CL},
  MaterialNew1 in 'Source\MaterialNew1.pas' {MaterialNew},
  PurOther_BJ1 in 'Source\SN213\PurOther_BJ1.pas' {PurOther_BJ},
  PurOther_Print1 in 'Source\SN213\PurOther_Print1.pas' {PurOther_Print},
  TraceNoSize1 in 'Source\TraceNoSize1.pas' {TraceNoSize},
  TraceSize1 in 'Source\TraceSize1.pas' {TraceSize},
  PurSize_BL1 in 'Source\SN212\PurSize_BL1.pas' {PurSize_BL},
  SonMaterial1 in 'Source\SonMaterial1.pas' {SonMaterial},
  PurList1 in 'Source\PurList1.pas' {PurList},
  ThreadBOM1 in 'Source\ThreadBOM1.pas' {ThreadBOM},
  ThreadBOM_CL1 in 'Source\ThreadBOM_CL1.pas' {ThreadBOM_CL},
  UseStock1 in 'Source\SN33\UseStock1.pas' {UseStock},
  EmbModel1 in 'Source\EmbModel1.pas' {EmbModel},
  EmbArticle1 in 'Source\EmbArticle1.pas' {EmbArticle},
  PurOther_safe1 in 'Source\SN213\PurOther_safe1.pas' {PurOther_safe},
  TraceList1 in 'Source\TraceList1.pas' {TraceList},
  PurNoSize_BL1 in 'Source\SN211\PurNoSize_BL1.pas' {PurNoSize_BL},
  PurchaseCheck1 in 'Source\PurchaseCheck1.pas' {PurchaseCheck},
  Purchasecheck_Det1 in 'Source\Purchasecheck_Det1.pas' {Purchasecheck_Det},
  DeliverTrace1 in 'Source\DeliverTrace1.pas' {DeliverTrace},
  DeliverTrace_Det1 in 'Source\DeliverTrace_Det1.pas' {DeliverTrace_Det},
  DeliverTraceS1 in 'Source\DeliverTraceS1.pas' {DeliverTraceS},
  QuotationRep1 in 'Source\QuotationRep1.pas' {QuotationRep},
  PurListTW1 in 'Source\PurListTW1.pas' {PurListTW},
  PurTotal1 in 'Source\SN214\PurTotal1.pas' {PurTotal},
  PurTotal_BJ1 in 'Source\SN214\PurTotal_BJ1.pas' {PurTotal_BJ},
  PurTatol_Cl1 in 'Source\SN214\PurTatol_Cl1.pas' {PurTatol_CL},
  PurTotal_ZS1 in 'Source\SN214\PurTotal_ZS1.pas' {PurTotal_ZS},
  PurTotal_Print1 in 'Source\SN214\PurTotal_Print1.pas' {PurTotal_Print},
  PurTotal_Safe1 in 'Source\SN214\PurTotal_Safe1.pas' {PurTotal_Safe},
  MaterialList1 in 'Source\MaterialList1.pas' {MaterialList},
  MaterialNew_LB1 in 'Source\MaterialNew_LB1.pas' {MaterialNew_LB},
  OrderSpec_Son1 in 'Source\OrderSpec_Son1.pas' {OrderSpec_Son},
  OrderSpec_Size1 in 'Source\OrderSpec_Size1.pas' {OrderSpec_Size},
  Purtrace1 in 'Source\SN31\Purtrace1.pas' {Purtrace},
  PurchaseAdjust1 in 'Source\PurchaseAdjust1.pas' {PurchaseAdjust},
  PurNoSize_Se1 in 'Source\SN211\PurNoSize_Se1.pas' {PurNoSize_Se},
  PartClass1 in 'Source\PartClass1.pas' {PartClass},
  UseStock_CL1 in 'Source\SN33\UseStock_CL1.pas' {UseStock_CL},
  Purtrace_Det1 in 'Source\SN31\Purtrace_Det1.pas' {Purtrace_Det},
  PurNoSize_Im1 in 'Source\SN211\PurNoSize_Im1.pas' {PurNoSize_Im},
  TraceTotal1 in 'Source\TraceTotal1.pas' {TraceTotal},
  PurchaseKPI1 in 'Source\SN25\PurchaseKPI1.pas' {purchasekpi},
  OMaterialListP in 'Source\OMaterialListP.pas' {OMaterialList},
  PurSampleFlowChart1 in 'source\SN78\PurSampleFlowChart1.pas' {PurSampleFlowChart},
  Articlecheck1 in 'source\SN731\Articlecheck1.pas' {Articlecheck},
  BOMReceive1 in 'source\SN711\BOMReceive1.pas' {BOMReceive},
  BOMReceive_Check1 in 'source\SN711\BOMReceive_Check1.pas' {BOMReceive_Check},
  CountryLeadtime1 in 'source\SN764\CountryLeadtime1.pas' {CountryLeadtime},
  ForwarderSample1 in 'source\SN761\ForwarderSample1.pas' {ForwarderSample},
  MaterialMOQ1 in 'source\SN764\MaterialMOQ1.pas' {MaterialMOQ},
  MaterialMOQ_Copy1 in 'source\SN764\MaterialMOQ_Copy1.pas' {MaterialMOQ_Copy},
  MaterialMOQ_LaceStyle1 in 'source\SN764\MaterialMOQ_LaceStyle1.pas' {MaterialMOQ_LaceStyle},
  MaterialMOQ_Purchaser1 in 'source\SN764\MaterialMOQ_Purchaser1.pas' {MaterialMOQ_Purchaser},
  MaterialNG1 in 'source\SN74\MaterialNG1.pas' {MaterialNG},
  PurConfirmPrice1 in 'source\SN753\PurConfirmPrice1.pas' {PurConfirmPrice},
  PurSample1 in 'source\SN731\PurSample1.pas' {PurSample},
  PurSampleInvoice_IM1 in 'source\SN751\PurSampleInvoice_IM1.pas' {PurSampleInvoice_IM},
  PurSampleInvoice1 in 'source\SN751\PurSampleInvoice1.pas' {PurSampleInvoice},
  PurSampleInvoice_Print1 in 'source\SN751\PurSampleInvoice_Print1.pas' {PurSampleInvoice_Print},
  PurSampleInvoice_PrintALL1 in 'source\SN751\PurSampleInvoice_PrintALL1.pas' {PurSampleInvoice_PrintALL},
  PurSampleInvoice_ZS1 in 'source\SN751\PurSampleInvoice_ZS1.pas' {PurSampleInvoice_ZS},
  PurSample_BJ1 in 'source\SN731\PurSample_BJ1.pas' {PurSample_BJ},
  Pursample_BW1 in 'source\SN731\Pursample_BW1.pas' {Pursample_BW},
  PurSample_CL1 in 'source\SN731\PurSample_CL1.pas' {PurSample_CL},
  PurSample_IM1 in 'source\SN731\PurSample_IM1.pas' {PurSample_IM},
  PurSample_Ord1 in 'source\SN731\PurSample_Ord1.pas' {PurSample_Ord},
  PurSample_Print_S1 in 'source\SN731\PurSample_Print_S1.pas' {PurSample_Print_S},
  Pursample_S1 in 'source\SN731\Pursample_S1.pas' {Pursample_S},
  PurSample_ZS1 in 'source\SN731\PurSample_ZS1.pas' {PurSample_ZS},
  QuotationS1 in 'source\SN731\QuotationS1.pas' {QuotationS},
  QuotationS_CL1 in 'source\SN731\QuotationS_CL1.pas' {QuotationS_CL},
  QuotationS_ZS1 in 'source\SN731\QuotationS_ZS1.pas' {QuotationS_ZS},
  SampleMerge1 in 'source\SN72\SampleMerge1.pas' {SampleMerge},
  SampleMerge_CL1 in 'source\SN72\SampleMerge_CL1.pas' {SampleMerge_CL},
  SamplePolicy1 in 'source\SN761\SamplePolicy1.pas' {SamplePolicy},
  SamplePolicy_Purchaser1 in 'source\SN761\SamplePolicy_Purchaser1.pas' {SamplePolicy_Purchaser},
  SamplePolicy_Style1 in 'source\SN761\SamplePolicy_Style1.pas' {SamplePolicy_Style},
  SupplierKPI1 in 'source\SN762\SupplierKPI1.pas' {SupplierKPI},
  SupplierKPI_Purchaser1 in 'source\SN762\SupplierKPI_Purchaser1.pas' {SupplierKPI_Purchaser},
  SupplierSample1 in 'source\SN763\SupplierSample1.pas' {SupplierSample},
  SupplierSample_Country1 in 'source\SN761\SupplierSample_Country1.pas' {SupplierSample_Country},
  SupplierSample_Group1 in 'source\SN761\SupplierSample_Group1.pas' {SupplierSample_Group},
  SupplierSample_Purchaser1 in 'source\SN761\SupplierSample_Purchaser1.pas' {SupplierSample_Purchaser},
  SupplierSample_PurchaserA1 in 'source\SN761\SupplierSample_PurchaserA1.pas' {SupplierSample_PurchaserA},
  SupplierSample_SamplePolicy1 in 'source\SN761\SupplierSample_SamplePolicy1.pas' {SupplierSample_SamplePolicy},
  SupplierSample_Style1 in 'source\SN761\SupplierSample_Style1.pas' {SupplierSample_Style},
  TraceListSample1 in 'source\SN733\TraceListSample1.pas' {TraceListSample},
  TraceListSample_Country1 in 'source\SN733\TraceListSample_Country1.pas' {TraceListSample_Country},
  TraceListSample_Purchaser1 in 'source\SN733\TraceListSample_Purchaser1.pas' {TraceListSample_Purchaser},
  TraceListSample_Style1 in 'source\SN733\TraceListSample_Style1.pas' {TraceListSample_Style},
  FDStatus_Article1 in 'source\SN733\FDStatus_Article1.pas' {FDStatus_Article},
  TraceSample1 in 'source\SN74\TraceSample1.pas' {TraceSample},
  TransportCharge1 in 'source\SN752\TransportCharge1.pas' {TransportCharge},
  SamplePurchaseAnalysis1 in 'source\SN734\SamplePurchaseAnalysis1.pas' {SamplePurchaseAnalysis},
  PurSample_SP1 in 'Source\SN731\PurSample_SP1.pas' {PurSample_SP},
  PurSample_SP_Detail1 in 'Source\SN731\PurSample_SP_Detail1.pas' {PurSample_SP_Detail},
  UseStockSample1 in 'source\SN712\UseStockSample1.pas' {UseStockSample},
  UseStockSample_CL1 in 'source\SN712\UseStockSample_CL1.pas' {UseStockSample_CL},
  AnyStock1 in 'source\SN713\AnyStock1.pas' {AnyStock},
  SampleSupplierAnalysis1 in 'source\SN732\SampleSupplierAnalysis1.pas' {SampleSupplierAnalysis},
  ChoiceArticle1 in 'Source\SN711\ChoiceArticle1.pas' {ChoiceArticle},
  GMS_RFT1 in 'Source\SN811\GMS_RFT1.pas' {GMS_RFT},
  Cons_AD1 in 'Source\SN765\Cons_AD1.pas' {Cons_AD},
  AD_Article1 in 'Source\SN765\AD_Article1.pas' {AD_Article},
  OrderSpecAll1 in 'Source\SN26\OrderSpecAll1.pas' {OrderSpecAll},
  PurOther_Dep1 in 'Source\SN213\PurOther_Dep1.pas' {PurOther_Dep},
  RYTemp1 in '..\Warehouse\Source\SN46\RYTemp1.pas' {RYTemp1},
  MaterialTrace1 in '..\Warehouse\Source\MaterialTrace1.pas' {MaterialTrace},
  MaterialTrace_Print1 in '..\Warehouse\Source\MaterialTrace_Print1.pas' {MaterialTrace_Print},
  MaterialTrace_JG1 in '..\Warehouse\Source\MaterialTrace_JG1.pas' {MaterialTrace_JG},
  MaterialTrace_JGA1 in '..\Warehouse\Source\MaterialTrace_JGA1.pas' {MaterialTrace_JGA},
  UseStockList1 in 'Source\SN351\UseStockList1.pas' {UseStockList},
  ColorSwatchCardTracking1 in 'Source\SN735\ColorSwatchCardTracking1.pas' {ColorSwatchCardTracking},
  Memo_En1 in 'Source\SN15\Memo_En1.pas' {Memo_En},
  ProduceUseStock1 in 'Source\SN352\ProduceUseStock1.pas' {ProduceUseStock},
  RSLSupplier1 in 'source\SN31\RSLSupplier1.pas' {RSLSupplier},
  RSLDDGB1 in 'source\SN31\RSLDDGB1.pas' {RSLDDGB},
  UpperMatInformation1 in 'Source\SN812\UpperMatInformation1.pas' {UpperMatInformation},
  PurtraceGC_Det1 in 'Source\SN36\PurtraceGC_Det1.pas' {PurtraceGC_Det},
  PurtraceGC1 in 'Source\SN36\PurtraceGC1.pas' {PurtraceGC},
  ExtraBW1 in 'Source\SN17\ExtraBW1.pas' {ExtraBW},
  SKU_ExtraCost1 in 'Source\SN17\SKU_ExtraCost1.pas' {SKU_ExtraCost},
  SKU_ExtraSupplier1 in 'Source\SN17\SKU_ExtraSupplier1.pas' {SKU_ExtraSupplier},
  TempMaterial1 in 'Source\SN736\TempMaterial1.pas' {TempMaterial},
  Exchange1 in 'Source\SN231\Exchange1.pas' {Exchange},
  MatDetailInformation1 in 'Source\SN813\MatDetailInformation1.pas' {MatDetailInformation},
  Exchange_NoSize1 in 'Source\SN211\Exchange_Nosize1.pas' {Exchange_Nosize},
  Exchange_Size1 in 'Source\SN212\Exchange_size1.pas' {Exchange_size},
  Exchange_PurSize1 in 'Source\SN213\Exchange_Pursize1.pas' {Exchange_Pursize},
  Quotation_XX1 in 'Source\SN231\Quotation_XX1.pas' {Quotation_XX},
  QuotationConCheckList1 in 'Source\SN232\QuotationConCheckList1.pas' {QuotationConCheckList},
  QuotationConCheck1 in 'Source\SN234\QuotationConCheck1.pas' {QuotationConCheck},
  SKU_ExtraXXZLS1 in 'Source\SN17\SKU_ExtraXXZLS1.pas' {SKU_ExtraXXZLS},
  QuotationConCheckList_Upload1 in 'Source\SN232\QuotationConCheckList_Upload1.pas' {QuotationConCheck},
  PurchaseKPI_Supp1 in 'Source\SN25\PurchaseKPI_Supp1.pas' {PurchaseKPI_Supp},
  GMS_RFT21 in 'Source\SN811\GMS_RFT21.pas' {GMS_RFT2},
  PriceChecking1 in 'Source\SN814\PriceChecking1.pas' {PriceChecking},
  TrackingPO_KCLL1 in 'Source\SN815\TrackingPO_KCLL1.pas' {TrackingPO_KCLL},
  Transportation1 in 'Source\SN7A\Transportation1.pas' {Transportation},
  SupplierSample_ZSDH_VN1 in 'Source\SN763\SupplierSample_ZSDH_VN1.pas' {SupplierSample_ZSDH_VN},
  PurNoSizeTW_Print1 in 'Source\SN211\PurNoSizeTW_Print1.pas' {PurNoSizeTW_Print},
  PurSizeTW_Print1 in 'Source\SN212\PurSizeTW_Print1.pas' {PurSizeTW_Print},
  PurOther_PrintTW1 in 'Source\SN213\PurOther_PrintTW1.pas' {PurOther_PrintTW},
  UPSupplier1 in 'Source\SN431\UPSupplier1.pas' {UPSupplier},
  UPQuotation1 in 'Source\SN432\UPQuotation1.pas' {UPQuotation},
  UPMaterial1 in 'Source\SN433\UPMaterial1.pas' {UPMaterial},
  UPMaterialQuery1 in 'Source\SN434\UPMaterialQuery1.pas' {UPMaterialQuery},
  UPOtherQuery1 in 'Source\SN435\UPOtherQuery1.pas' {UPOtherQuery},
  UPSupplierCountry1 in 'Source\SN431\UPSupplierCountry1.pas' {UPSupplierCountry},
  UPSupplierGroup1 in 'Source\SN431\UPSupplierGroup1.pas' {UPSupplierGroup},
  UPSupplierName1 in 'Source\SN431\UPSupplierName1.pas' {UPSupplierName},
  UPQuotationName1 in 'Source\SN432\UPQuotationName1.pas' {UPQuotationName},
  UPStyleGroup1 in 'Source\SN432\UPStyleGroup1.pas' {UPStyleGroup},
  UPSelectMaterial1 in 'Source\SN433\UPSelectMaterial1.pas' {UPSelectMaterial},
  UPSupplierName_N7431 in 'Source\SN433\UPSupplierName_N7431.pas' {UPSupplierName_N743},
  UPSelectStyle1 in 'Source\SN432\UPSelectStyle1.pas' {UPSelectStyle},
  PurSample_Print_Tw1 in 'Source\SN731\PurSample_Print_Tw1.pas' {PurSample_Print_Tw},
  PurTotalTW_Print1 in 'Source\SN214\PurTotalTW_Print1.pas' {PurTotalTW_Print},
  FileTransClient1 in 'Source\SN31\FileTransClient1.pas',
  Purtrace_LT1 in 'Source\SN31\Purtrace_LT1.pas' {Purtrace_LT},
  untClipboard in 'Source\SN31\untClipboard.pas',
  Flexcode1 in 'Source\SN737\Flexcode1.pas' {FlexCode},
  ConfirmSwatchReport1 in 'Source\SN816\ConfirmSwatchReport1.pas' {ConfirmSwatchReport},
  Vendor1 in 'Source\SN816\Vendor1.pas' {Vendor},
  Purchaselist_Det1 in 'Source\SN7B\Purchaselist_Det1.pas' {Purchaselist_Det},
  Purchaselist1 in 'Source\SN7B\Purchaselist1.pas' {Purchaselist},
  PurtraceMatch1 in 'Source\SN37\PurtraceMatch1.pas' {PurtraceMatch},
  ProdSupplierKPI1 in 'Source\SN252\ProdSupplierKPI1.pas' {ProdSupplierKPI},
  PurtraceMatch_OrderExcel1 in 'Source\SN37\PurtraceMatch_OrderExcel1.pas' {PurtraceMatch_OrderExcel},
  PurtraceMatch_NoNeedPurchase1 in 'Source\SN37\PurtraceMatch_NoNeedPurchase1.pas' {PurtraceMatch_NoNeedPurchase},
  TraceChangeMaterial1 in 'Source\SN79\TraceChangeMaterial1.pas' {TraceChangeMaterial},
  Pur_Replenish1 in 'Source\SN213\Pur_Replenish1.pas' {Pur_Replenish},
  PurOtherSizeTW_Print1 in 'Source\SN213\PurOtherSizeTW_Print1.pas' {PurOtherSizeTW_Print},
  Material_Pre1 in 'Source\SN281\Material_Pre1.pas' {Material_Pre},
  MaterialOrder_Pre1 in 'Source\SN281\MaterialOrder_Pre1.pas' {MaterialOrder_Pre},
  Reality_Remain_Quantity_Pre1 in 'Source\SN281\Reality_Remain_Quantity_Pre1.pas' {Reality_Remain_Quantity_Pre},
  PreOrder_UseStock1 in 'Source\SN282\PreOrder_UseStock1.pas' {PreOrder_UseStock},
  ZSZL_Pre1 in 'Source\SN281\ZSZL_Pre1.pas' {ZSZL_Pre},
  Reality_Remain_Quantity_Pre_Print1 in 'Source\SN281\Reality_Remain_Quantity_Pre_Print1.pas' {Reality_Remain_Quantity_Pre_Print},
  Reality_Remain_Quantity_Pre_Print21 in 'Source\SN281\Reality_Remain_Quantity_Pre_Print21.pas' {Reality_Remain_Quantity_Pre_Print2},
  DeliverTraceOther1 in 'Source\SN323\DeliverTraceOther1.pas' {DeliverTraceO},
  UseStock_KCZK1 in 'Source\SN33\UseStock_KCZK1.pas' {UseStock_KCZK},
  PreOrder_Calcuate1 in 'Source\SN280\PreOrder_Calcuate1.pas' {PreOrder_Calcuate},
  PreOrder_XXZLS1 in 'Source\SN280\PreOrder_XXZLS1.pas' {PreOrder_XXZLS},
  PreOrder_Print1 in 'Source\SN280\PreOrder_Print1.pas' {PreOrder_Print},
  Reality_Remain_Quantity_Pre_YGNO1 in 'Source\SN281\Reality_Remain_Quantity_Pre_YGNO1.pas' {Reality_Remain_Quantity_Pre_YGNO},
  Quotation_CGBJ1 in 'Source\SN231\Quotation_CGBJ1.pas' {Quotation_CGBJ},
  RP_Acceptance in 'Source\SN731\RP_Acceptance.pas' {RP_Acceptance},
  Modelmaterialfee1 in 'Source\SN817\Modelmaterialfee1.pas' {Modelmaterialfee},
  PurchaseConfirmShoes1 in 'Source\SN7C\PurchaseConfirmShoes1.pas' {PurchaseConfirmShoes},
  CFMSwatchTracKing1 in 'Source\SN38\CFMSwatchTracKing1.pas' {CFMSwatchTracKing},
  CBYSize1 in 'Source\SN7D\CBYSize1.pas' {CBYSize},
  CBYSizeComparison1 in 'Source\SN738\CBYSizeComparison1.pas' {CBYSizeComparison},
  PurRevise1 in 'Source\SN731\PurRevise1.pas' {PurRevise},
  Pur_Choice1 in 'Source\SN731\Pur_Choice1.pas' {Pur_Choice},
  MaterialAllowanceSetting1 in 'Source\SN91\MaterialAllowanceSetting1.pas' {MaterialAllowanceSetting},
  PO_Permission1 in 'Source\SN92\PO_Permission1.pas' {PO_Permission},
  PurSample_CBY1 in 'Source\SN731\PurSample_CBY1.pas' {PurSample_CBY},
  PurSample_CBY_Detail1 in 'Source\SN731\PurSample_CBY_Detail1.pas' {PurSample_CBY_Detail},
  CFMSwatchDatabase1 in 'Source\SN739\CFMSwatchDatabase1.pas' {CFMSwatchDatabase},
  ApplyTotal1 in 'Source\SN2151\ApplyTotal1.pas' {ApplyTotal},
  ApplyTotalDepName1 in 'Source\SN2151\ApplyTotalDepName1.pas' {ApplyTotalDepName},
  ApplyTotalMatNo1 in 'Source\SN2151\ApplyTotalMatNo1.pas' {ApplyTotalMatNo},
  ApplyTotal_Print1 in 'Source\SN2151\ApplyTotal_Print1.pas' {ApplyTotal_Print},
  PurTotal_SGDH1 in 'Source\SN214\PurTotal_SGDH1.pas' {PurTotal_SGDH},
  TraceApplyTotal1 in 'Source\SN225\TraceApplyTotal1.pas' {TraceApply},
  HangTagDate1 in 'Source\SN751\HangTagDate1.pas' {HangTagDate},
  PurTotal_Replenish1 in 'Source\SN214\PurTotal_Replenish1.pas' {PurTotal_Replenish},
  Barcode1281 in 'Source\SN751\Barcode1281.pas' {Barcode128},
  ApplyTotalConfirm1 in 'Source\SN2152\ApplyTotalConfirm1.pas' {ApplyTotalConfirm},
  ApplyPurTotal_BJ1 in 'Source\SN2151\ApplyPurTotal_BJ1.pas' {ApplyPurTotal_BJ},
  ApplyTotalConfirm21 in 'Source\SN2153\ApplyTotalConfirm21.pas' {ApplyTotalConfirm2},
  ApplyMold_Print1 in 'Source\SN740\ApplyMold_Print1.pas' {ApplyMold_Print},
  ApplyMold_PrintZSDH1 in 'Source\SN740\ApplyMold_PrintZSDH1.pas' {ApplyMold_PrintZSDH},
  ApplyMold1 in 'Source\SN740\ApplyMold1.pas' {ApplyMold},
  ApplyMoldDepName1 in 'Source\SN740\ApplyMoldDepName1.pas' {ApplyMoldDepName},
  ApplyMoldMatNo1 in 'Source\SN740\ApplyMoldMatNo1.pas' {ApplyMoldMatNo},
  ApplyPurMold_BJ1 in 'Source\SN740\ApplyPurMold_BJ1.pas' {ApplyPurMold_BJ},
  TotalApplyReport_Print1 in 'Source\SN226\TotalApplyReport_Print1.pas' {TotalApplyReport_Print},
  TotalApplyReport1 in 'Source\SN226\TotalApplyReport1.pas' {TotalApplyReport},
  ProcurementValue1 in 'Source\SN818\ProcurementValue1.pas' {ProcurementValue},
  RP_AcceptanceSize1 in 'Source\SN731\RP_AcceptanceSize1.pas' {RP_AcceptanceSize},
  CGNOConfirm1 in 'Source\SN2161\CGNOConfirm1.pas' {CGNOConfirm},
  CGNOConfirm21 in 'Source\SN2162\CGNOConfirm21.pas' {CGNOConfirm2},
  OriginVATNo1 in 'Source\SN29\OriginVATNo1.pas' {OriginVATNo},
  ApplyTotalCheck1 in 'Source\SN21541\ApplyTotalCheck1.pas' {ApplyTotalCheck},
  SupplierReview_MonthlyReport1 in 'Source\SN52\SupplierReview_MonthlyReport1.pas' {SupplierReview_MonthlyReport},
  SupplierReview_SeasonalReport1 in 'Source\SN52\SupplierReview_SeasonalReport1.pas' {SupplierReview_SeasonalReport},
  SupplierReview_Supplier1 in 'Source\SN52\SupplierReview_Supplier1.pas' {SupplierReview_Supplier},
  SupplierReview1 in 'Source\SN52\SupplierReview1.pas' {SupplierReview},
  ColorStandardDatabase1 in 'Source\SN741\ColorStandardDatabase1.pas' {ColorStandardDatabase},
  ShowShoePic1 in 'Source\SN741\ShowShoePic1.pas' {ShowShoePic},
  PurSample_Ord_New1 in 'Source\SN731\PurSample_Ord_New1.pas' {PurSample_Ord_New},
  PurTotal_SGDep1 in 'Source\SN214\PurTotal_SGDep1.pas' {PurTotal_SGDep},
  Budget_Setting1 in 'Source\SN227\Budget_Setting1.pas' {Budget_Setting},
  FileOriginMaterial1 in 'Source\SN39\FileOriginMaterial1.pas' {FileOriginMaterial},
  SupplierReview_ZSDH1 in 'Source\SN52\SupplierReview_ZSDH1.pas' {SupplierReview_ZSDH},
  Traceability_Purchasing1 in 'Source\SN3A1\Traceability_Purchasing1.pas' {Traceability_Purchasing},
  OriginMaterial1 in 'Source\SN2A\OriginMaterial1.pas' {OriginMaterial},
  ZlQuery1 in 'Source\SN3B\ZlQuery1.pas' {ZlQuery},
  SupplierSaleContract1 in 'Source\SN2B\SupplierSaleContract1.pas' {SupplierSaleContract},
  ChooseSupplier1 in 'Source\SN2B\ChooseSupplier1.pas' {ChooseSupplier},
  Upload_PLX1 in 'Source\SN2C\Upload_PLX1.pas' {Upload_PLX},
  VendorColorKPI_ZS1 in 'Source\SN742\VendorColorKPI_ZS1.pas' {VendorColorKPI_ZS},
  VendorColorKPI1 in 'Source\SN742\VendorColorKPI1.pas' {VendorColorKPI},
  Traceability_Purchasing_Chemical1 in 'Source\SN3A2\Traceability_Purchasing_Chemical1.pas' {Traceability_Purchasing_Chemical},
  SupplierReviewDevelop1 in 'Source\SN53\SupplierReviewDevelop1.pas' {SupplierReviewDevelop},
  SupplierReview_Supplier_Dev1 in 'Source\SN53\SupplierReview_Supplier_Dev1.pas' {SupplierReview_Supplier_Dev},
  SupplierReviewDevelop_MonthlyReport1 in 'Source\SN53\SupplierReviewDevelop_MonthlyReport1.pas' {SupplierReviewDevelop_MonthlyReport},
  Choose_Supplier_Dev1 in 'Source\SN53\Choose_Supplier_Dev1.pas' {Choose_Supplier_Dev},
  SupplierReviewDevelop_SeasonalReport1 in 'Source\SN53\SupplierReviewDevelop_SeasonalReport1.pas' {SupplierReviewDevelop_SeasonalReport},
  Season_Set1 in 'Source\SN93\Season_Set1.pas' {Season_Set},
  FDstatus_Season1 in 'Source\SN93\FDstatus_Season1.pas' {FDstatus_Season},
  FDstatus_Stage1 in 'Source\SN93\FDstatus_Stage1.pas' {FDstatus_Stage},
  SGDH_STOCK1 in 'Source\SN228\SGDH_STOCK1.pas' {SGDH_Stock},
  Choice_CLBH1 in 'Source\SN228\Choice_CLBH1.pas' {Choice_CLBH},
  PaymentQuotation1 in 'Source\SN7E\PaymentQuotation1.pas' {PaymentQuotation},
  PurNoSizeTW_Print_TW1 in 'Source\SN211\PurNoSizeTW_Print_TW1.pas' {PurNoSizeTW_Print_TW},
  PurNoSizeTW_Print_VN1 in 'Source\SN211\PurNoSizeTW_Print_VN1.pas' {PurNoSizeTW_Print_VN},
  PurSizeTW_Print_TW1 in 'Source\SN212\PurSizeTW_Print_TW1.pas' {PurSizeTW_Print_TW},
  PurSizeTW_Print_VN1 in 'Source\SN212\PurSizeTW_Print_VN1.pas' {PurSizeTW_Print_VN},
  PurOther_PrintTW_TW1 in 'Source\SN213\PurOther_PrintTW_TW1.pas' {PurOther_PrintTW_TW},
  PurOther_PrintTW_VN1 in 'Source\SN213\PurOther_PrintTW_VN1.pas' {PurOther_PrintTW_VN},
  PurSample_Print_Tw_Approve1 in 'Source\SN731\PurSample_Print_Tw_Approve1.pas' {PurSample_Print_Tw_Approve},
  PurSample_Print_Tw_Normal1 in 'Source\SN731\PurSample_Print_Tw_Normal1.pas' {PurSample_Print_Tw_Normal},
  PurSample_Print_Tw_NoSize1 in 'Source\SN731\PurSample_Print_Tw_NoSize1.pas' {PurSample_Print_Tw_NoSize},
  PurSample_Print_Tw_NoSize_Normal1 in 'Source\SN731\PurSample_Print_Tw_NoSize_Normal1.pas' {PurSample_Print_Tw_NoSize_Normal},
  TraceStock1 in 'Source\SN714TraceStock\TraceStock1.pas' {TraceStock},
  PurPham_Replenish1 in 'Source\SN213\PurPham_Replenish1.pas' {PurPham_Replenish},
  PurOtherSizeTW_Print_VN1 in 'Source\SN213\PurOtherSizeTW_Print_VN1.pas' {PurOtherSizeTW_Print_VN},
  AutoSaveA4CFM1 in 'Source\SN735\AutoSaveA4CFM1.pas' {AutoSaveA4CFM},
  Detail1 in 'Source\SN3C\Detail1.pas' {Detail},
  OrderControlRecord_Print1 in 'Source\SN3C\OrderControlRecord_Print1.pas' {OrderControlRecord_Print},
  OrderControlRecord1 in 'Source\SN3C\OrderControlRecord1.pas' {OrderControlRecord},
  MassMatMOQ1 in 'Source\SN2D\MassMatMOQ1.pas' {MassMatMOQ},
  ApplyPhom_Print1 in 'Source\SN217\ApplyPhom_Print1.pas' {ApplyPhom_Print},
  ApplyPhom1 in 'Source\SN217\ApplyPhom1.pas' {ApplyPhom},
  ApplyPhomDepName1 in 'Source\SN217\ApplyPhomDepName1.pas' {ApplyPhomDepName},
  ApplyPhomMatNo1 in 'Source\SN217\ApplyPhomMatNo1.pas' {ApplyPhomMatNo},
  ApplyPurPhom_BJ1 in 'Source\SN217\ApplyPurPhom_BJ1.pas' {ApplyPurPhom_BJ},
  SupplierBPM1 in 'Source\SN766\SupplierBPM1.pas' {SupplierBPM},
  History1 in 'Source\SN7F\History1.pas' {History},
  RequestCheckStock1 in 'Source\SN7F\RequestCheckStock1.pas' {RequestCheckStock},
  SetCommonMat1 in 'Source\SN7G\SetCommonMat1.pas' {SetCommonMat},
  SetMaterial1 in 'Source\SN7G\SetMaterial1.pas' {SetMaterial},
  ColorGroup_History1 in 'Source\SN764\ColorGroup_History1.pas' {ColorGroup_History},
  ForeCast_Purchase_Compare1 in 'Source\SN3D\ForeCast_Purchase_Compare1.pas' {ForeCast_Purchase_Compare},
  Apply_Purchase_Printing_Mold_DepName1 in 'Source\SN743\Apply_Purchase_Printing_Mold_DepName1.pas' {Apply_Purchase_Printing_Mold_DepName},
  Apply_Purchase_Printing_Mold_MatNo1 in 'Source\SN743\Apply_Purchase_Printing_Mold_MatNo1.pas' {Apply_Purchase_Printing_Mold_MatNo},
  Apply_Purchase_Printing_Mold_Print1 in 'Source\SN743\Apply_Purchase_Printing_Mold_Print1.pas' {Apply_Purchase_Printing_Mold_Print},
  Apply_Purchase_Printing_Mold1 in 'Source\SN743\Apply_Purchase_Printing_Mold1.pas' {Apply_Purchase_Printing_Mold},
  ApplyTotalCapex1 in 'Source\SN2151\ApplyTotalCapex1.pas' {ApplyTotalCapex},
  MaterialWovenList1 in 'Source\SN18\MaterialWovenList1.pas' {MaterialWovenList},
  VLAReport1 in 'Source\SN7H\VLAReport1.pas' {VLAReport},
  PercenReport1 in 'Source\SN3E\PercenReport1.pas' {PercenReport},
  MaterialOnTimeArrivalRate1 in 'Source\SN3F\MaterialOnTimeArrivalRate1.pas' {MaterialOnTimeArrivalRate},
  ESG_CLBH1 in 'Source\SN101\ESG_CLBH1.pas' {ESG},
  CLBH_Weight1 in 'Source\SN102\CLBH_Weight1.pas' {CLBH_Weight},
  ZSZL_ESG1 in 'Source\SN103\ZSZL_ESG1.pas' {ZSZL_ESG};

{$R *.res}


var
  MutexHandle: THandle;
begin
  MutexHandle := Windows.CreateMutex(Nil, true, 'Purchase.exe');
  if (MutexHandle <> 0) then
  begin
    if (GetLastError = Windows.ERROR_ALREADY_EXISTS) then
    begin
      CloseHandle(MutexHandle);
      Halt;
    end;
  end;
  Application.Initialize;
  login := Tlogin.Create(Application);
  login.Show;
  login.Update;
  Application.Title := 'LaiYih ERP-Purchase';
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(Tmain, main);
  Application.CreateForm(TPurSampleFlowChart, PurSampleFlowChart);
  login.Hide;
  login.Free;
  Application.Run;
end.
