program Production;

uses
  Forms,
  Windows,
  main1 in 'source\main1.pas' {main},
  ulogin in 'source\ulogin.pas' {LOGIN},
  DM3 in 'source\DM3.pas' {DM2: TDataModule},
  Ontime1 in 'source\Ontime1.pas' {Ontime},
  OnTime_Dep1 in 'source\OnTime_Dep1.pas' {OnTime_Dep},
  OnTime_sczl1 in 'source\OnTime_sczl1.pas' {OnTime_sczl},
  OrderCheck1 in 'source\OrderCheck1.pas' {OrderCheck},
  DailyRep1 in 'source\DailyRep1.pas' {DailyRep},
  OrderCheck_Det1 in 'source\OrderCheck_Det1.pas' {OrderCheck_Det},
  MonthRep1 in 'source\MonthRep1.pas' {MonthRep},
  Planoutput1 in 'source\Planoutput1.pas' {Planoutput},
  SpecPrint1 in 'source\SpecPrint1.pas' {SpecPrint},
  NewReplenish1 in 'source\NewReplenish1.pas' {NewReplenish},
  Replenishinsert1 in 'source\Replenishinsert1.pas' {Replenishinsert},
  Produceset1 in 'source\Produceset1.pas' {Produceset},
  NewreplenishPart1 in 'source\NewreplenishPart1.pas' {NewreplenishPart},
  ReplenishPart_order1 in 'source\ReplenishPart_order1.pas' {ReplenishPart_order},
  NewreplenishLR1 in 'source\NewreplenishLR1.pas' {NewreplenishLR},
  Newreplenishparts1 in 'source\Newreplenishparts1.pas' {Newreplenishparts},
  PSpecPrintss1 in 'source\PSpecPrintss1.pas' {PSpecPrintss},
  Delperson1 in 'source\Delperson1.pas' {Delperson},
  DelMaterial1 in 'source\SN311\DelMaterial1.pas' {DelMaterial},
  DelMaterial_Dep1 in 'source\SN311\DelMaterial_Dep1.pas' {DelMaterial_Dep},
  DelMaterial_CL1 in 'source\SN311\DelMaterial_CL1.pas' {DelMaterial_CL},
  DelMaterial_Print1 in 'source\SN311\DelMaterial_Print1.pas' {DelMaterial_Print},
  DelOther1 in 'source\SN321\DelOther1.pas' {DelOther},
  DelOther_Dep1 in 'source\SN321\DelOther_Dep1.pas' {DelOther_Dep},
  DelOther_CL1 in 'source\SN321\DelOther_CL1.pas' {DelOther_CL},
  DelOther_Mat1 in 'source\SN321\DelOther_Mat1.pas' {DelOther_Mat},
  DelOther_Print1 in 'source\SN321\DelOther_Print1.pas' {DelOther_Print},
  Produceset_size1 in 'source\Produceset_size1.pas' {Produceset_size},
  DelOther_C1 in 'source\SN312\DelOther_C1.pas' {DelOther_C},
  DelOther_C_Dep1 in 'source\SN312\DelOther_C_Dep1.pas' {DelOther_C_Dep},
  DelOther_C_Print1 in 'source\SN312\DelOther_C_Print1.pas' {DelOther_C_Print},
  DelCheck1 in 'source\DelCheck1.pas' {DelCheck},
  NewRep_Print1 in 'source\NewRep_Print1.pas' {NewRep_Print},
  NewRepPart_Print1 in 'source\NewRepPart_Print1.pas' {NewRepPart_Print},
  ArticleType1 in 'source\ArticleType1.pas' {ArticleType},
  DelOther_YY1 in 'source\SN321\DelOther_YY1.pas' {DelOther_YY},
  ReplenishReason1 in 'source\ReplenishReason1.pas' {ReplenishReason},
  DelOther_SCBH1 in 'source\SN321\DelOther_SCBH1.pas' {DelOther_SCBH},
  PackingPrint1 in 'source\PackingPrint1.pas' {PackingPrint},
  packingPrint_P1 in 'source\packingPrint_P1.pas' {packingPrint_P},
  DelOther_O1 in 'source\SN322\DelOther_O1.pas' {DelOther_O},
  DelOther_O_Dep1 in 'source\SN322\DelOther_O_Dep1.pas' {DelOther_O_Dep},
  DelOther_O_CL1 in 'source\SN322\DelOther_O_CL1.pas' {DelOther_O_CL},
  DelOther_O_Print1 in 'source\SN322\DelOther_O_Print1.pas' {DelOther_O_Print},
  DelOther_O_YY1 in 'source\SN322\DelOther_O_YY1.pas' {DelOther_O_YY},
  PSpecPrintssTW1 in 'source\PSpecPrintssTW1.pas' {PSpecPrintssTW},
  MaterialPre1 in 'source\MaterialPre1.pas' {MaterialPre},
  SpecPrint_Temp1 in 'source\SpecPrint_Temp1.pas' {SpecPrint_Temp},
  DeloverPre1 in 'source\DeloverPre1.pas' {DeloverPre},
  SpecPrint_VNBOM1 in 'source\SpecPrint_VNBOM1.pas' {SpecPrint_VNBOM},
  PlanDate1 in 'source\PlanDate1.pas' {PlanDate},
  Purtrace1 in 'source\Purtrace1.pas' {Purtrace},
  DelMaterial_CT1 in 'source\SN311\DelMaterial_CT1.pas' {DelMaterial_CT},
  DeliverRep1 in 'source\DeliverRep1.pas' {DeliverRep},
  SpecPrint_Change1 in 'source\SpecPrint_Change1.pas' {SpecPrint_Change},
  ScanIn1 in 'source\SN511\ScanIn1.pas' {ScanIn},
  ScanIn_Dep1 in 'Source\SN511\ScanIn_Dep1.pas' {ScanIn_Dep},
  DelOther_Conton1 in 'source\SN313\DelOther_Conton1.pas' {DelOther_Conton},
  DelOther_Carton_Print1 in 'source\SN313\DelOther_Carton_Print1.pas' {DelOther_Carton_Print},
  DelOther_Carton_Dep1 in 'source\SN313\DelOther_Carton_Dep1.pas' {DelOther_Carton_Dep},
  DelOther_Carton_CL1 in 'source\SN313\DelOther_Carton_CL1.pas' {DelOther_Carton_CL},
  ScanInspect1 in 'source\ScanInspect1.pas' {ScanInspect},
  ScanInSelect1 in 'source\ScanInSelect1.pas' {ScanInSelect},
  ScanOut1 in 'source\SN5131\ScanOut1.pas' {ScanOut},
  ScanShip1 in 'source\ScanShip1.pas' {ScanShip},
  ScanStock1 in 'source\ScanStock1.pas' {ScanStock},
  ScanStockBrand1 in 'source\ScanStockBrand1.pas' {ScanStockBrand},
  ScanStockBrand_Det1 in 'source\ScanStockBrand_Det1.pas' {ScanStockBrand_Det},
  ScanDailyDep1 in 'source\ScanDailyDep1.pas' {ScanDailyDep},
  ScanDailyDep_Det1 in 'source\ScanDailyDep_Det1.pas' {ScanDailyDep_Det},
  ScanDailyRep1 in 'source\ScanDailyRep1.pas' {ScanDailyRep},
  ScanDailyRep_det1 in 'source\ScanDailyRep_det1.pas' {ScanDailyRep_det},
  ScanStockDet1 in 'source\ScanStockDet1.pas' {ScanStockDet},
  ScanStockMon1 in 'source\ScanStockMon1.pas' {ScanStockMon},
  ScanInbox1 in 'source\SN53\ScanInbox1.pas' {ScanInbox},
  ScanStockDet_Det1 in 'source\ScanStockDet_Det1.pas' {ScanStockDet_Det},
  ScanStockDet_Car1 in 'source\ScanStockDet_Car1.pas' {ScanStockDet_Car},
  ScanShip_hand1 in 'source\ScanShip_hand1.pas' {ScanShip_hand},
  ScanOut_hand1 in 'source\SN5131\ScanOut_hand1.pas' {ScanOut_hand},
  ScanInspect_hand1 in 'source\ScanInspect_hand1.pas' {ScanInspect_hand},
  ScanIn_hand1 in 'source\SN511\ScanIn_hand1.pas' {ScanIn_hand},
  ScanExport1 in 'source\ScanExport1.pas' {ScanExport},
  ScanExport_Det1 in 'source\ScanExport_Det1.pas' {ScanExport_Det},
  ScanOutRep1 in 'source\SN5241\ScanOutRep1.pas' {ScanOutRep},
  ScanInspectRep1 in 'source\ScanInspectRep1.pas' {ScanInspectRep},
  ScanOutRep_Det1 in 'source\SN5241\ScanOutRep_Det1.pas' {ScanOutRep_Det},
  ScanInspectRep_Det1 in 'source\ScanInspectRep_Det1.pas' {ScanInspectRep_Det},
  DelOther_C_Mat1 in 'source\SN312\DelOther_C_Mat1.pas' {DelOther_C_Mat},
  DelOther_D1 in 'source\SN323\DelOther_D1.pas' {DelOther_D},
  DelOther_D_Dep1 in 'source\SN323\DelOther_D_Dep1.pas' {DelOther_D_Dep},
  DelOther_D_CL1 in 'source\SN323\DelOther_D_CL1.pas' {DelOther_D_CL},
  DelOther_D_YY1 in 'source\SN323\DelOther_D_YY1.pas' {DelOther_D_YY},
  DelOther_D_Print1 in 'source\SN323\DelOther_D_Print1.pas' {DelOther_D_Print},
  DelOther_C_SCBH1 in 'source\SN312\DelOther_C_SCBH1.pas' {DelOther_C_SCBH},
  ScanInbox_GB1 in 'source\SN53\ScanInbox_GB1.pas' {ScanInbox_GB},
  ScanAccountMon1 in 'source\ScanAccountMon1.pas' {ScanAccountMon},
  ScanInspectOrd1 in 'source\ScanInspectOrd1.pas' {ScanInspectOrd},
  Report6021 in 'source\Report6021.pas' {Report602},
  Report602_det1 in 'source\Report602_det1.pas' {Report602_det},
  ScanCheck1 in 'source\ScanCheck1.pas' {ScanCheck},
  DelChemical1 in 'source\SN3241\DelChemical1.pas' {DelChemical},
  DelChemical_Dep1 in 'source\SN3241\DelChemical_Dep1.pas' {DelChemical_Dep},
  DelChemical_CL1 in 'source\SN3241\DelChemical_CL1.pas' {DelChemical_CL},
  DelChemical_Mat1 in 'source\SN3241\DelChemical_Mat1.pas' {DelChemical_Mat},
  DelChemical_Print1 in 'source\SN3241\DelChemical_Print1.pas' {DelChemical_Print},
  DelChemical_SCBH1 in 'source\SN3241\DelChemical_SCBH1.pas' {DelChemical_SCBH},
  ReplenishDel1 in 'source\SN24\ReplenishDel1.pas' {ReplenishDel},
  ReplenishDel_ZL1 in 'source\SN24\ReplenishDel_ZL1.pas' {ReplenishDel_ZL},
  ReplenishDel_Dep1 in 'source\SN24\ReplenishDel_Dep1.pas' {ReplenishDel_Dep},
  ReplenishDel_YY1 in 'source\SN24\ReplenishDel_YY1.pas' {ReplenishDel_YY},
  ReplenishDel_Print1 in 'source\SN24\ReplenishDel_Print1.pas' {ReplenishDel_Print},
  ReplenishDel_MulitRY1 in 'source\SN24\ReplenishDel_MulitRY1.pas' {ReplenishDel_MulitRY},
  ReplenishDel_PrintMergNo1 in 'source\SN24\ReplenishDel_PrintMergNo1.pas' {ReplenishDel_PrintMergNo},
  ReplenishCon1 in 'source\ReplenishCon1.pas' {ReplenishCon},
  DelOther_BL1 in 'source\SN321\DelOther_BL1.pas' {DelOther_BL},
  adsimportP in 'source\adsimportP.pas' {Adsimport},
  ReplenishAnlysisP in '..\Manage\source\ReplenishAnlysisP.pas' {ReplenishAnlysis},
  replenishanlysisdP in '..\Manage\source\replenishanlysisdP.pas' {ReplenishAnlysisd},
  StockAnlysisp in 'source\StockAnlysisp.pas' {StockAnlysis},
  shipoutp in 'source\shipoutp.pas' {ShipingOut},
  GIFImage in '..\..\delphicomponent\GifImage\D7\gifimage.pas',
  SpecImport1 in 'source\SN11\SpecImport1.pas' {SpecImport},
  SpecimportCheck1 in 'source\SN11\SpecimportCheck1.pas' {SpecimportCheck},
  SpecimportTW1 in 'source\SN11\SpecimportTW1.pas' {SpecimportTW},
  ArticlePicP in 'source\SN19\ArticlePicP.pas' {ArticlePic},
  ArticlePicQP in 'source\SN19\ArticlePicQP.pas' {ArticlePicQ},
  ScanIn_InUser1 in 'source\SN511\ScanIn_InUser1.pas' {ScanIn_User},
  LLMaterial1 in 'source\SN323\LLMaterial1.pas' {LLMaterial},
  BShoeZLZL1 in 'source\SN16\BShoeZLZL1.pas' {BShoeZLZL},
  PSPecPrintss_SP1 in 'source\SN16\PSPecPrintss_SP1.pas' {PSpecPrintss_SP},
  DelOther_Mat_CL1 in 'source\SN312\DelOther_Mat_CL1.pas' {DelOther_Mat_CL},
  LLMaterialSR1 in 'source\SN323\LLMaterialSR1.pas' {LLMaterialSR},
  ScanBanDo1 in 'source\SN516\ScanBanDo1.pas' {ScanBanDo},
  ScanBanDo_RY1 in 'source\SN516\ScanBanDo_RY1.pas' {ScanBanDo_RY},
  ExportQuantity1 in 'source\SN526\ExportQuantity1.pas' {ExportQuantity},
  ExcelSheetDlg1 in '..\Plan\Source\SN545\ExcelSheetDlg1.pas' {ExcelSheetDlg},
  DelChemical_Rep1 in 'source\SN3242\DelChemical_Rep1.pas' {DelChemical_Rep},
  DelChemical_RepCL1 in 'source\SN3242\DelChemical_RepCL1.pas' {DelChemical_RepCL},
  DelChemical_RepPrint1 in 'source\SN3242\DelChemical_RepPrint1.pas' {DelChemical_RepPrint},
  DelOther_INK_CL1 in 'source\SN314\DelOther_INK_CL1.pas' {DelOther_INK_CL},
  DelOther_INK_Dep1 in 'source\SN314\DelOther_INK_Dep1.pas' {DelOther_INK_Dep},
  DelOther_INK_Mat1 in 'source\SN314\DelOther_INK_Mat1.pas' {DelOther_INK_Mat},
  DelOther_INK_Print1 in 'source\SN314\DelOther_INK_Print1.pas' {DelOther_INK_Print},
  DelOther_INK_SCBH1 in 'source\SN314\DelOther_INK_SCBH1.pas' {DelOther_INK_SCBH},
  DelOther_INK1 in 'source\SN314\DelOther_INK1.pas' {DelOther_INK},
  Tachdonhang1 in 'source\SN11\Tachdonhang1.pas' {Tachdonhang},
  CD_Department1 in 'source\SN42\CD_Department1.pas' {CD_Department},
  CD_Rotation1 in 'source\SN42\CD_Rotation1.pas' {CD_Rotation},
  CutDispatch1 in 'source\SN42\CutDispatch1.pas' {CutDispatch},
  CD_SMDD1 in 'source\SN42\CD_SMDD1.pas' {CD_SMDD},
  CD_SMDDS1 in 'source\SN42\CD_SMDDS1.pas' {CD_SMDDS},
  CD_Print1 in 'source\SN42\CD_Print1.pas' {CD_Print},
  QRPDFFilt in 'source\SN42\qrpdffilt.pas',
  CD_QuickSMDD1 in 'source\SN42\CD_QuickSMDD1.pas' {CD_QuickSMDD},
  Barcode93Unit1 in 'source\SN42\Barcode93Unit1.pas',
  CutDispatchZL1 in 'source\SN16\CutDispatchZL1.pas' {CutDispatchZL},
  DelMat_Byhand1 in 'source\SN325\DelMat_Byhand1.pas' {DelMat_Byhand},
  DelMat_Byhand_YY1 in 'source\SN325\DelMat_Byhand_YY1.pas' {DelMat_Byhand_YY},
  DelMat_Byhand_Mat1 in 'source\SN325\DelMat_Byhand_Mat1.pas' {DelMat_Byhand_Mat},
  DelMat_Byhand_Print1 in 'source\SN325\DelMat_Byhand_Print1.pas' {DelMat_Byhand_Print},
  DelMat_Byhand_Dep1 in 'source\SN325\DelMat_Byhand_Dep1.pas' {DelMat_Byhand_Dep},
  CD_PrintH1 in 'source\SN42\CD_PrintH1.pas' {CD_PrintH},
  untClipboard in 'source\SN11\untClipboard.pas',
  DelMaterial_DDZLTR1 in 'source\SN311\DelMaterial_DDZLTR1.pas' {DelMaterial_DDZLTR},
  DelMaterial_PrintS1 in 'source\SN311\DelMaterial_PrintS1.pas' {DelMaterial_PrintS},
  CutDispatchZL_GC1 in 'source\SN16\CutDispatchZL_GC1.pas' {CutDispatchZL_GC},
  CPD_Department1 in 'source\SN43\CPD_Department1.pas' {CPD_Department},
  CPD_ZLBH1 in 'source\SN43\CPD_ZLBH1.pas' {CPD_ZLBH},
  CutProcessDispatch1 in 'source\SN43\CutProcessDispatch1.pas' {CutProcessDispatch},
  CDGC_SMDDS1 in 'source\SN43\CDGC_SMDDS1.pas' {CDGC_SMDDS},
  CD_SMDDList1 in 'source\SN42\CD_SMDDList1.pas' {CD_SMDDList},
  CuttingType1 in 'source\SN42\CuttingType1.pas' {CuttingType},
  CD_PrintHDlg1 in 'source\SN42\CD_PrintHDlg1.pas' {CD_PrintHDlg},
  CD_MatCLSLRpt1 in 'source\SN42\CD_MatCLSLRpt1.pas' {CD_MatCLSLRpt},
  CD_PrintH21 in 'source\SN42\CD_PrintH21.pas' {CD_PrintH2},
  CutMachineComparison1 in 'source\SN44\CutMachineComparison1.pas' {CutMachineComparison},
  CutProcessDispatch_SMDD1 in 'source\SN43\CutProcessDispatch_SMDD1.pas' {CutProcessDispatch_SMDD},
  SMDDCycRound1 in 'source\SN45\SMDDCycRound1.pas' {SMDDCycRound},
  CutMachine1 in 'source\SN46\CutMachine1.pas' {CutMachine},
  MachineType1 in 'source\SN46\MachineType1.pas' {MachineType},
  SetMachineData1 in 'source\SN44\SetMachineData1.pas' {SetMachineData},
  CPD_QuickDispatch1 in 'source\SN43\CPD_QuickDispatch1.pas' {CPD_QuickDispatch},
  CutProcessImport1 in 'source\SN43\CutProcessImport1.pas' {CutProcessImport},
  PD_PrintH1 in 'source\SN43\PD_PrintH1.pas' {PD_PrintH},
  PD_PrintHDlg1 in 'source\SN43\PD_PrintHDlg1.pas' {PD_PrintHDlg},
  CD_LectraMerg1 in 'source\SN42\CD_LectraMerg1.pas' {CD_LectraMerg},
  CD_LectraLayerout1 in 'source\SN42\CD_LectraLayerout1.pas' {CD_LectraLayerout},
  OrderCopy1 in 'source\SN42\OrderCopy1.pas' {OrderCopy},
  MachineLean1 in 'source\SN46\MachineLean1.pas' {MachineLean},
  MachineSelect1 in 'source\SN42\MachineSelect1.pas' {MachineSelect},
  LLMaterial_Detail1 in 'source\SN323\LLMaterial_Detail1.pas' {LLMaterial_Detail},
  DelOther_TSCD1 in 'Source\SN326\DelOther_TSCD1.pas' {DelOther_TSCD},
  QRCode1 in 'Source\SN326\QRCode1.pas' {QRCodeForm},
  DelphiZXingQRCode in 'source\SN326\DelphiZXIngQRCode.pas',
  GC_Search1 in 'source\SN43\GC_Search1.pas' {GC_Search},
  Set_Pur_Delivery1 in 'source\SN16\Set_Pur_Delivery1.pas' {Set_Pur_Delivery},
  DeloverPre_Print1 in 'source\SN36\DeloverPre_Print1.pas' {DeloverPre_Print},
  StockShoeMonth1 in 'source\SN5216\StockShoeMonth1.pas' {StockShoeMonth},
  ScanReturn1 in 'source\SN5132\ScanReturn1.pas' {ScanReturn},
  ScanReturnRep1 in 'source\SN5242\ScanReturnRep1.pas' {ScanReturnRep},
  ScanReturn_hand1 in 'source\SN5132\ScanReturn_hand1.pas' {ScanReturn_hand},
  ScanReturnRep_Det1 in 'source\SN5242\ScanReturnRep_Det1.pas' {ScanReturnRep_Det},
  DelOther_KI1 in 'source\SN315\DelOther_KI1.pas' {DelOther_KI},
  DelOther_KI_Dep1 in 'source\SN315\DelOther_KI_Dep1.pas' {DelOther_KI_Dep},
  DelOther_KI_CL1 in 'source\SN315\DelOther_KI_CL1.pas' {DelOther_KI_CL},
  DelOther_KI_Mat1 in 'source\SN315\DelOther_KI_Mat1.pas' {DelOther_KI_Mat},
  DelOther_KI_SCBH1 in 'source\SN315\DelOther_KI_SCBH1.pas' {DelOther_KI_SCBH},
  DelOther_KI_Print1 in 'source\SN315\DelOther_KI_Print1.pas' {DelOther_KI_Print},
  StockShoeMonth_TRList1 in 'source\SN5216\StockShoeMonth_TRList1.pas' {StockShoeMonth_TRList},
  LLNOConfirm1 in 'source\SN3A11\LLNOConfirm1.pas' {LLNOConfirm},
  LLNOConfirm21 in 'source\SN3A12\LLNOConfirm21.pas' {LLNOConfirm2},
  LLNOConfirm31 in 'source\SN3A13\LLNOConfirm31.pas' {LLNOConfirm3},
  scandata_Print1 in 'source\SN527\scandata_Print1.pas' {scandata_Print},
  scandata1 in 'source\SN527\scandata1.pas' {ScanData},
  scandataout1 in 'source\SN527\scandataout1.pas' {scandataout},
  DelOther_O_PrintTB1 in 'source\SN322\DelOther_O_PrintTB1.pas' {DelOther_O_PrintTB},
  FGKeyInOrder1 in 'source\SN55\FGKeyInOrder1.pas' {FGKeyInOrder},
  StockShoeMonth_Print1 in 'source\SN5216\StockShoeMonth_Print1.pas' {StockShoeMonth_Print},
  StockShoeMonthRe_Print1 in 'source\SN5216\StockShoeMonthRe_Print1.pas' {StockShoeMonthRe_Print},
  InventoryTurnoverDays1 in 'source\SN528\InventoryTurnoverDays1.pas' {InventoryTurnoverDays},
  Replenish_Stamp1 in 'source\SN26\Replenish_Stamp1.pas' {Replenish_Stamp},
  Replenish_Stamp_Dep1 in 'source\SN26\Replenish_Stamp_Dep1.pas' {Replenish_Stamp_Dep},
  Replenish_Stamp_CL1 in 'source\SN26\Replenish_Stamp_CL1.pas' {Replenish_Stamp_CL},
  Replenish_Stamp_YY1 in 'source\SN26\Replenish_Stamp_YY1.pas' {Replenish_Stamp_YY},
  Replenish_Stamp_SCBH1 in 'source\SN26\Replenish_Stamp_SCBH1.pas' {Replenish_Stamp_SCBH},
  scandata_Print_Total1 in 'source\SN527\scandata_Print_Total1.pas' {scandata_Print_Total},
  Scandata_Report1 in 'source\SN527\Scandata_Report1.pas' {Scandata_Report},
  Scandata_Print_TotalAll1 in 'source\SN527\Scandata_Print_TotalAll1.pas' {Scandata_Print_TotalAll},
  MassPro_PrintCard1 in 'source\SN5216\MassPro_PrintCard1.pas' {MassPro_PrintCard};

{$R *.res}

var   MutexHandle:Thandle;
begin
  Mutexhandle:=windows.CreateMutex(nil,true,'Production.exe');
  if   Mutexhandle<>0   then
    begin
      if   getlasterror=windows.ERROR_ALREADY_EXISTS   then
        begin
          closehandle(Mutexhandle);
          halt;
        end;
    end;
  Application.Initialize;
  login:=tlogin.create(application);
  login.Show;
  login.Update;
  Application.Title := 'LaiYih ERP -Production';
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(Tmain, main);
  login.hide;
  login.free;
  Application.Run;

end.
