program shipping;

uses
  Forms,
  main1 in 'main1.pas' {main},
  DM1 in 'DM1.pas' {DM: TDataModule},
  NumberToWords in 'source\SN11\NumberToWords.pas',
  MakeInvoice1 in 'source\SN11\MakeInvoice1.pas' {MakeInvoice},
  AddRy1 in 'source\SN12\AddRy1.pas' {AddRy},
  Contract_Inv_Print1 in 'source\SN12\Contract_Inv_Print1.pas' {Contract_Inv_Print},
  InvoicePL1 in 'source\SN12\InvoicePL1.pas' {InvoicePL},
  Pwd1 in 'source\SN12\Pwd1.pas' {Pwd},
  QpInvoice1 in 'source\SN12\QpInvoice1.pas' {QpInvoice},
  QpPackingList1 in 'source\SN12\QpPackingList1.pas' {QpPackingList},
  RYPrice1 in 'source\SN21\RYPrice1.pas' {RYPrice},
  ImportRYPrice1 in 'source\SN21\ImportRYPrice1.pas' {ImportRYPrice},
  Invoice_SelectOrder1 in 'Source\SN11\Invoice_SelectOrder1.pas' {Invoice_SelectOrder},
  ShippingFlowChart1 in 'Source\ShippingFlowChart1.pas' {ShippingFlowChart},
  DetailInVNo1 in 'Source\SN13\DetailInVNo1.pas' {DetailInVNo},
  DetailInVNO_Det1 in 'Source\SN13\DetailInVNO_Det1.pas' {DetailInVNO_Det},
  EntryCheck_Print1 in '..\Account\Source\EntryCheck_Print1.pas' {EntryCheck_Print},
  EntryCheck1 in '..\Account\Source\EntryCheck1.pas' {EntryCheck},
  SampleOrder1 in 'Source\SN41\SampleOrder1.pas' {SampleOrder},
  Bomshipping11 in 'Source\SN31\Bomshipping11.pas' {Bomshipping1},
  Deliveraccount_Detail1 in 'Source\SN33\Deliveraccount_Detail1.pas' {Deliveraccount_Detail},
  DeliverAccount1 in 'Source\SN33\DeliverAccount1.pas' {DeliverAccount},
  ShipReviseUsage1 in 'Source\SN32\ShipReviseUsage1.pas' {ShipReviseUsage},
  WareStock1 in 'Source\SN14\WareStock1.pas' {WareStock},
  WareStock_Det1 in 'Source\SN14\WareStock_Det1.pas' {WareStock_Det},
  DDZL_BOMM1 in '..\BOM\source\SN53\DDZL_BOMM1.pas' {BOMM},
  D_PSPecPrintss_SP1 in '..\BOM\source\SN53\D_PSPecPrintss_SP1.pas' {D_PSpecPrintss_SP},
  D_PSpecPrintssTW1 in '..\BOM\source\SN53\D_PSpecPrintssTW1.pas' {D_PSpecPrintssTW},
  D_PSpecPrintss1 in 'Source\SN32\D_PSpecPrintss1.pas' {D_PSpecPrintss},
  R_PSepcRintss1 in '..\BOM\source\SN53\R_PSepcRintss1.pas',
  ShipRevise_CLZL1 in 'Source\SN32\ShipRevise_CLZL1.pas' {ShipRevise_CLZL},
  DetailInSampleOrder1 in 'Source\SN42\DetailInSampleOrder1.pas' {DetailInSampleOrder},
  DetailInSampleOrderList1 in 'Source\SN42\DetailInSampleOrderList1.pas' {DetailInSampleOrderList},
  WareStock_MDet1 in 'Source\SN14\WareStock_MDet1.pas' {WareStock_MDet},
  ShipDateConfirm1 in 'Source\SN43\ShipDateConfirm1.pas' {ShipDateConfirm},
  choosedetail1 in 'Source\SN43\choosedetail1.pas' {ChooseDetail},
  CustomsShoes1 in 'Source\SN92\CustomsShoes1.pas' {CustomsShoes},
  ShippingDestroy1 in 'Source\SN93\ShippingDestroy1.pas' {ShippingDestroy},
  ShippingExportOrderList1 in 'Source\SN94\ShippingExportOrderList1.pas' {ShippingExportOrderList},
  YPZLShipReviseUsage_CLZL1 in 'Source\SN44\YPZLShipReviseUsage_CLZL1.pas' {YPZLShipReviseUsage_CLZL},
  YPZLShipReviseUsage1 in 'Source\SN44\YPZLShipReviseUsage1.pas' {YPZLShipReviseUsage},
  YPZL_BOMM1 in 'Source\SN45\YPZL_BOMM1.pas' {YPZL_BOMM},
  YPZLShipReviseUsage_BWBH1 in 'Source\SN44\YPZLShipReviseUsage_BWBH1.pas' {YPZLShipReviseUsage_BWBH},
  MaHQvaMaHD1 in 'Source\SN17\MaHQvaMaHD1.pas' {MaHQvaMaHD},
  untClipboard in 'Source\SN13\untClipboard.pas',
  CGZL2CNO_CGNO1 in 'Source\SN51\CGZL2CNO_CGNO1.pas' {CGZL2CNO_CGNO},
  CGZL2CNO1 in 'Source\SN51\CGZL2CNO1.pas' {CGZL2CNO},
  QHWH2CNO_HQNO1 in 'Source\SN52\QHWH2CNO_HQNO1.pas' {QHWH2CNO_HQNO},
  QWHS2CNO1 in 'Source\SN52\QWHS2CNO1.pas' {QWHS2CNO},
  QWHSRpt1 in 'Source\SN53\QWHSRpt1.pas' {QWHSRpt},
  ShippingConfirmShoes1 in 'Source\SN46\ShippingConfirmShoes1.pas' {ShippingConfirmShoes},
  DevtoSimis1 in 'Source\SN47\DevtoSimis1.pas' {DevtoSimis},
  SplitInvoice_RY1 in 'Source\SN22\SplitInvoice_RY1.pas' {SplitInvoice_RY},
  SplitInvoice1 in 'Source\SN22\SplitInvoice1.pas' {SplitInvoice},
  MergeInvoice1 in 'Source\SN23\MergeInvoice1.pas' {MergeInvoice},
  Booking1 in 'Source\SN61\Booking1.pas' {Booking},
  Forwarder1 in 'Source\SN61\Forwarder1.pas' {Forwarder},
  KindLoading1 in 'Source\SN61\KindLoading1.pas' {KindLoading},
  PlaceDelivery1 in 'Source\SN61\PlaceDelivery1.pas' {PlaceDelivery},
  DelayReason1 in 'Source\SN61\DelayReason1.pas' {DelayReason},
  DozcBill1 in 'Source\SN62\DozcBill1.pas' {DozcBill},
  DoczCO1 in 'Source\SN63\DoczCO1.pas' {DoczCO},
  DoczCO_PrintInv_O1 in 'Source\SN63\DoczCO_PrintInv_O1.pas' {DoczCO_PrintInv_O},
  DoczCO_PrintInv1 in 'Source\SN63\DoczCO_PrintInv1.pas' {DoczCO_PrintInv},
  FormCO_ANNZ_Print1 in 'Source\SN63\FormCO_ANNZ_Print1.pas' {FormCO_ANNZ_Print},
  FormCO_TR_Print1 in 'Source\SN63\FormCO_TR_Print1.pas' {FormCO_TR_Print},
  FormCO_VC_Print1 in 'Source\SN63\FormCO_VC_Print1.pas' {FormCO_VC_Print},
  Import_Customs1 in 'Source\SN63\Import_Customs1.pas' {Import_Customs},
  Import_HSCode1 in 'Source\SN63\Import_HSCode1.pas' {Import_HSCode},
  FormCO_AJ_Print1 in 'Source\SN63\FormCO_AJ_Print1.pas' {FormCO_AJ_Print},
  WareStock_Print1 in 'Source\SN14\WareStock_Print1.pas' {WareStock_Print},
  TWShippingOrderList1 in 'Source\SN95\TWShippingOrderList1.pas' {TWShippingOrderList},
  MakeInvoiceTW1 in 'Source\SN71\MakeInvoiceTW1.pas' {MakeInvoiceTW},
  InvoicePL_TW1 in 'Source\SN72\InvoicePL_TW1.pas' {InvoicePL_TW},
  HGUsage1 in 'Source\SN1A\HGUsage1.pas' {HGUsage},
  Bill_Info1 in 'Source\SNA1\Bill_Info1.pas' {Bill_Info},
  Traceability_Material_Receiving1 in 'Source\SN96\Traceability_Material_Receiving1.pas' {Traceability_Material_Receiving},
  MaHaiQuan1 in 'Source\SN151\MaHaiQuan1.pas' {MaHaiQuan},
  TimMaHQ1 in 'Source\SN151\TimMaHQ1.pas' {TimMaHQ},
  MaHoaDon1 in 'Source\SN161\MaHoaDon1.pas' {MaHoaDon},
  TimMaHD1 in 'Source\SN161\TimMaHD1.pas' {TimMaHD},
  MaHaiQuanTC1 in 'Source\SN181\MaHaiQuanTC1.pas' {MaHaiQuanTC},
  TimMaTC1 in 'Source\SN181\TimMaTC1.pas' {TimMaTC},
  MaHaiQuanKD1 in 'Source\SN191\MaHaiQuanKD1.pas' {MaHaiQuanKD},
  TimMaKD1 in 'Source\SN191\TimMaKD1.pas' {TimMaKD},
  MaHaiQuan_NK1 in 'Source\SN152\MaHaiQuan_NK1.pas' {MaHaiQuan_NK},
  TimMHQ_NK1 in 'Source\SN152\TimMHQ_NK1.pas' {TimMHQ_NK},
  MaHoaDon_HD1 in 'Source\SN162\MaHoaDon_HD1.pas' {MaHoaDon_HD},
  TimMaHoaDon1 in 'Source\SN162\TimMaHoaDon1.pas' {TimMaHoaDon},
  MaHaiQuan_TC1 in 'Source\SN182\MaHaiQuan_TC1.pas' {MaHaiQuan_TC},
  TimMa_TC1 in 'Source\SN182\TimMa_TC1.pas' {TimMa_TC},
  MaHaiQuan_KD1 in 'Source\SN192\MaHaiQuan_KD1.pas' {MaHaiQuan_KD},
  TimMa_KD1 in 'Source\SN192\TimMa_KD1.pas' {TimMa_KD},
  Bill_ShippingFG1 in 'Source\SNA2\Bill_ShippingFG1.pas' {Bill_ShippingFG},
  Traceability_Shipping_FG1 in 'Source\SN97\Traceability_Shipping_FG1.pas' {Traceability_Shipping_FG},
  MaHaiQuanNQ1 in 'Source\SN1B\MaHaiQuanNQ1.pas' {MaHaiQuanNQ},
  TimMaHQNQ1 in 'Source\SN1B\TimMaHQNQ1.pas' {TimMaHQNQ},
  MaHaiQuanNKNQ1 in 'Source\SN1C\MaHaiQuanNKNQ1.pas' {MaHaiQuanNKNQ},
  TimMaHQNKNQ1 in 'Source\SN1C\TimMaHQNKNQ1.pas' {TimMaHQNKNQ},
  MaiHaiQuan14161 in 'Source\SN15A\MaiHaiQuan14161.pas' {MaiHaiQuan1416},
  TimMaHQN15A1 in 'Source\SN15A\TimMaHQN15A1.pas' {TimMaHQN15A},
  ImportHaiQuan1 in 'Source\SN35\ImportHaiQuan1.pas' {ImportHaiQuan},
  ShippingUsage1 in 'Source\SN35\ShippingUsage1.pas' {ShippingUsage},
  ScanInvoice1 in 'Source\SNB1\ScanInvoice1.pas' {ScanInvoice};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TDM, DM);
  Application.CreateForm(Tmain, main);
  Application.CreateForm(TShippingFlowChart, ShippingFlowChart);
  Application.Run;
  application.Terminate;
end.
