program QC;

uses
  Forms,
  Windows,
  main1 in 'source\main1.pas' {main},
  ulogin in 'source\ulogin.pas' {LOGIN},
  DM3 in 'source\DM3.pas' {DM2: TDataModule},
  Ontime1 in 'source\Ontime1.pas' {Ontime},
  OnTime_Dep1 in 'source\OnTime_Dep1.pas' {OnTime_Dep},
  OnTime_sczl1 in 'source\OnTime_sczl1.pas' {OnTime_sczl},
  QCOntime1 in 'source\QCOntime1.pas' {QCOntime},
  QCOnTime_Query1 in 'source\QCOnTime_Query1.pas' {QCOnTime_Query},
  QCOnTime_sczl1 in 'source\QCOnTime_sczl1.pas' {QCOnTime_sczl},
  QCOnTime_XH1 in 'source\QCOnTime_XH1.pas' {QCOnTime_XH},
  QCMonthlyReport_Print_P1 in 'source\QCMonthlyReport_Print_P1.pas' {QCMonthlyReport_Print_P},
  QCMonthlyReport1 in 'source\QCMonthlyReport1.pas' {QCMonthlyReport},
  QCMonthlyReport_Print1 in 'source\QCMonthlyReport_Print1.pas' {QCMonthlyReport_Print},
  QCMonthlyReport_Print_A1 in 'source\QCMonthlyReport_Print_A1.pas' {QCMonthlyReport_Print_A},
  FeedbackWastrelOnSite in 'source\FeedbackWastrelOnSite.pas' {FmFeedbackWastrelOnSite},
  QCDailyReport_Print1 in 'source\QCDailyReport_Print1.pas' {QCDailyReport_Print},
  QCDailyReport_Print_P1 in 'source\QCDailyReport_Print_P1.pas' {QCDailyReport_Print_P},
  QCDailyReport_Print_A1 in 'source\QCDailyReport_Print_A1.pas' {QCDailyReport_Print_A},
  QCDailyReport_Print_C1 in 'source\QCDailyReport_Print_C1.pas' {QCDailyReport_Print_C},
  QCOnTime_Dep1 in 'source\QCOnTime_Dep1.pas' {QCOnTime_Dep},
  QCIssue1 in 'source\QCIssue1.pas' {QCIssue},
  QCQueryList1 in 'source\QCQueryList1.pas' {QCQueryList},
  QCDailyData1 in 'source\QCDailyData1.pas' {QCDailyData},
  QCDailyReport1 in 'source\QCDailyReport1.pas' {QCDailyReport},
  RYCheck_Det1 in 'source\RYCheck_Det1.pas' {RYCheck_Det},
  RYCheckM_Det1 in 'source\RYCheckM_Det1.pas' {RYCheckM_Det},
  DailyTotal1 in 'source\DailyTotal1.pas' {DailyTotal},
  QAStationP in 'Source\QAStationP.pas' {QAStation},
  VOC_Chart1 in 'Source\VOC_Chart1.pas' {VOC_Chart},
  VOC_Input_Dep1 in 'Source\VOC_Input_Dep1.pas' {VOC_Input_Dep},
  VOC_Input1 in 'Source\VOC_Input1.pas' {VOC_Input},
  VOC_List1 in 'Source\VOC_List1.pas' {VOC_List},
  Cement1 in 'Source\Cement1.pas' {Cement},
  Inspectp in 'Source\Inspectp.pas' {Inspect},
  IQCLISTP in 'Source\IQCLISTP.pas' {IQCLIST},
  ShoesIOP in 'Source\ShoesIOP.pas' {ShoesIO},
  BCSHOESP in 'Source\BCSHOESP.pas' {BCSHOES},
  BCSSOP in 'Source\BCSSOP.pas' {BCSSO},
  QCXXCJP in 'Source\QCXXCJP.pas' {QCXXCJ},
  QCXXCJ_XXP in 'Source\QCXXCJ_XXP.pas' {QCXXCJ_XX},
  QC_BatchInputp in 'Source\SN5B\QC_BatchInputp.pas' {QC_BatchInput},
  ShoeBC1 in 'Source\SN56\ShoeBC1.pas' {ShoeBC},
  QC_DailyBonding1 in 'Source\SN711\QC_DailyBonding1.pas' {QC_DailyBonding},
  Department1 in 'Source\SN711\Department1.pas' {Department},
  Article1 in 'Source\SN711\Article1.pas' {Article},
  Order1 in 'Source\SN711\Order1.pas' {Order},
  TestItem_Standard1 in 'Source\SN711\TestItem_Standard1.pas' {TestItem_Standard},
  QC_FinishShoe_Standard_Input1 in 'Source\SN5C\QC_FinishShoe_Standard_Input1.pas' {QC_FinishShoe_Standard_Input},
  QC_FinishShoe_StandardItem1 in 'Source\SN712\QC_FinishShoe_StandardItem1.pas' {QC_FinishShoe_StandardItem},
  QC_FinishShoeStandard1 in 'Source\SN712\QC_FinishShoeStandard1.pas' {QC_FinishShoeStandard},
  QCFlowChart1 in 'Source\SN16\QCFlowChart1.pas' {QCFlowChart},
  QC_FailReasonList1 in 'Source\SN711\QC_FailReasonList1.pas' {QC_FailReasonList},
  AndonInputRev1 in 'Source\SN56\AndonInputRev1.pas' {AndonInputRev},
  QCOnTime_DepRev1 in 'Source\SN56\QCOnTime_DepRev1.pas' {QCOnTime_DepRev},
  ClsReport in 'Source\SN722\ClsReport.pas',
  QC_MatDefect1 in 'Source\SN721\QC_MatDefect1.pas' {QC_MatDefect},
  QCOnTime_GXLB1 in 'Source\SN56\QCOnTime_GXLB1.pas' {QCOnTime_GXLB},
  MQRBDP in 'Source\SN56\MQRBDP.pas' {MQRBD},
  MatQcCheck1 in 'Source\SN721\MatQcCheck1.pas' {MatQcCheck},
  LeatherSummary1 in 'Source\SN722\LeatherSummary1.pas' {LeatherSummary},
  Leather_supp1 in 'Source\SN722\Leather_supp1.pas' {Leather_supp},
  Leather_standard1 in 'Source\SN722\Leather_standard1.pas' {Leather_standard},
  Leather_SummaryMat1 in 'Source\SN722\Leather_SummaryMat1.pas' {Leather_SummaryMat},
  RYDetail_S1 in 'Source\SN721\RYDetail_S1.pas' {RYDetail_S},
  Calculator1 in 'Source\SN721\Calculator1.pas' {Calculator},
  DailyReport1 in 'Source\SN723\DailyReport1.pas' {DailyReport},
  RYDetail1 in 'Source\SN721\RYDetail1.pas' {RYDetail},
  MatLabCheck1 in 'Source\SN724\MatLabCheck1.pas' {MatLabCheck},
  Lab_TestReason1 in 'Source\SN724\Lab_TestReason1.pas' {Lab_TestReason},
  FileTransClient1 in 'Source\SN721\FileTransClient1.pas' {FileTransClient},
  Brand1 in 'Source\SN724\Brand1.pas' {Brand},
  TestItem1 in 'Source\SN73\TestItem1.pas' {TestItem},
  Shoetest1 in 'Source\SN74\Shoetest1.pas' {ShoeTest},
  TestItemChoose1 in 'Source\SN74\TestItemChoose1.pas' {TestItemChoose},
  UploadFile1 in 'Source\SN74\UploadFile1.pas' {UploadFile},
  SampleRYDetail1 in 'Source\SN721\SampleRYDetail1.pas' {SampleRYDetail},
  MatLabCheck_Upload1 in 'Source\SN724\MatLabCheck_Upload1.pas' {MatLabCheck_Upload},
  MaterialTest1 in 'Source\SN75\MaterialTest1.pas' {MaterialTest},
  Import_Excel_To_MsSQL1 in 'Source\SN75\Import_Excel_To_MsSQL1.pas' {Import_Excel_To_MsSQL},
  QCConfirmShoes1 in 'Source\SN5D\QCConfirmShoes1.pas' {QCConfirmShoes},
  AndonAlarmSetting1 in 'Source\SN5E\AndonAlarmSetting1.pas' {AndonAlarmSetting},
  AndonDepartment1 in 'Source\SN5E\AndonDepartment1.pas' {AndonDepartment},
  AndonDefect1 in 'Source\SN5E\AndonDefect1.pas' {AndonDefect},
  StockIn_BC1 in 'Source\SN36\StockIn_BC1.pas' {StockIn_BC},
  Department_BC1 in 'Source\SN36\Department_BC1.pas' {Department_BC},
  OrderList_BC1 in 'Source\SN36\OrderList_BC1.pas' {OrderList_BC},
  Inventory_BC1 in 'Source\SN35\Inventory_BC1.pas' {Inventory_BC},
  StockOut_BC1 in 'Source\SN37\StockOut_BC1.pas' {StockOut_BC},
  OrderListOut_BC1 in 'Source\SN37\OrderListOut_BC1.pas' {OrderListOut_BC},
  UploadExcleReport1 in 'Source\SN724\UploadExcleReport1.pas' {UploadExcleReport},
  StockIn_Report1 in 'Source\SN36\StockIn_Report1.pas' {StockIn_Report},
  StockOut_Report1 in 'Source\SN37\StockOut_Report1.pas' {StockOut_Report},
  BGradeOrders1 in 'Source\SN38\BGradeOrders1.pas' {BGradeOrders},
  StockOut_ScrapReport1 in 'Source\SN37\StockOut_ScrapReport1.pas' {StockOut_ScrapReport},
  RejectMaterial1 in 'Source\SN76\RejectMaterial1.pas' {RejectMaterial},
  RejectMat1 in 'Source\SN76\RejectMat1.pas' {RejectMat},
  RejectRY1 in 'Source\SN76\RejectRY1.pas' {RejectRY},
  Claim_Report1 in 'Source\SN77\Claim_Report1.pas' {Claim_Report},
  Factory_Claim1 in 'Source\SN77\Factory_Claim1.pas' {Factory_Claim},
  Article_Claim1 in 'Source\SN77\Article_Claim1.pas' {Article_Claim},
  ClaimAnalytics1 in 'Source\SN77\ClaimAnalytics1.pas' {ClaimAnalytics},
  OrderList1 in 'Source\SN77\OrderList1.pas' {OrderList},
  untClipboard in 'Source\SN77\untClipboard.pas',
  OutsoleInspection1 in 'Source\SN5F\OutsoleInspection1.pas' {OutsoleInspection},
  OutsoleInspection_Outsole1 in 'Source\SN5F\OutsoleInspection_Outsole1.pas' {OutsoleInspection_OutSole},
  OutsoleInspection_SKU1 in 'Source\SN5F\OutsoleInspection_SKU1.pas' {OutsoleInspection_SKU},
  OutsoleInspection_Size1 in 'Source\SN5F\OutsoleInspection_Size1.pas' {OutsoleInspection_Size},
  OutsoleInspectionReport1 in 'Source\SN78\OutsoleInspectionReport1.pas' {OutsoleInspectionReport},
  PIList1 in 'Source\SN79\PIList1.pas' {PIList},
  RCA1 in 'Source\SN7A\RCA1.pas' {RCA},
  MA_Inspection_Dep1 in 'Source\SN44\MA_Inspection_Dep1.pas' {MA_Inspection_Dep},
  MA_Inspection_rpt1 in 'Source\SN44\MA_Inspection_rpt1.pas' {MA_Inspection_rpt},
  MA_Inspection_RY1 in 'Source\SN44\MA_Inspection_RY1.pas' {MA_Inspection_RY},
  MA_Inspection_Showimg1 in 'Source\SN44\MA_Inspection_Showimg1.pas' {MA_Inspection_Showimg},
  MA_Inspection1 in 'Source\SN44\MA_Inspection1.pas' {MA_Inspection},
  MA_Inspectiontakephoto1 in 'Source\SN44\MA_Inspectiontakephoto1.pas' {MA_Inspectiontakephoto},
  MA_Repacking1 in 'Source\SN45\MA_Repacking1.pas' {MA_Repacking},
  MA_ActionPlan1 in 'Source\SN46\MA_ActionPlan1.pas' {MA_ActionPlan},
  Stock_Out_Report1 in 'Source\SN392\Stock_Out_Report1.pas' {StockOut_BC_Report},
  Stock_In_Report1 in 'Source\SN391\Stock_In_Report1.pas' {Stock_In_Report},
  CBY_QC1 in 'Source\SN5G1\CBY_QC1.pas' {CBY_QC},
  pngimage in 'Source\SN5G1\PNGImage.pas',
  pnglang in 'Source\SN5G1\pnglang.pas',
  zlibpas in 'Source\SN5G1\zlibpas.pas',
  CBYQCREPORT1 in 'Source\SN5G2\CBYQCREPORT1.pas' {CBYQCReport},
  Ma_Cartons1 in 'Source\SN47\Ma_Cartons1.pas' {MaCartons},
  AndonInputRev_AE1 in 'Source\SN5H\AndonInputRev_AE1.pas' {AndonInputRev_AE},
  QCOnTime_DepRev_AE1 in 'Source\SN5H\QCOnTime_DepRev_AE1.pas' {QCOnTime_DepRev_AE},
  QCOnTime_GXLB_AE1 in 'Source\SN5H\QCOnTime_GXLB_AE1.pas' {QCOnTime_GXLB_AE},
  QC_Report1 in 'Source\SN82\QC_Report1.pas' {QC_Report},
  QCScanReport1 in 'Source\SN5I\QCScanReport1.pas' {QCScanReport},
  QCDefectReport1 in 'Source\SN5I\QCDefectReport1.pas' {QCDefectReport},
  QCMonthDfect1 in 'Source\SN5I\QCMonthDfect1.pas' {QCMonthDefect},
  QCSpecialDefect1 in 'Source\SN5I\QCSpecialDefect1.pas' {QCSpecialDefect},
  R_Factory_QC1 in 'Source\SN5J1\R_Factory_QC1.pas' {R_Factory_QC},
  CheckingReport1 in 'Source\SN83\CheckingReport1.pas' {CheckingReport},
  R_Factory_QCReport1 in 'Source\SN5J2\R_Factory_QCReport1.pas' {R_Factory_QCReport},
  MA_Box1 in 'Source\SN48\MA_Box1.pas' {MA_Box},
  Thung_DepName1 in 'Source\SN48\Thung_DepName1.pas' {Thung_DepName},
  Inspection_report1 in 'Source\SN471\Inspection_report1.pas' {Inspection_report},
  Single_inspection_report1 in 'Source\SN472\Single_inspection_report1.pas' {Single_inspection_report},
  QCParamtConfig in 'Source\SN5K\QCParamtConfig.pas' {QC_Parmat_Config},
  RY_Inspection_Status1 in 'Source\SN49\RY_Inspection_Status1.pas' {RY_Inspection_Status},
  Failed_Cartons_Input_Depname1 in 'Source\SN4A\Failed_Cartons_Input_Depname1.pas' {Failed_Cartons_Input_Depname},
  Failed_Cartons_Input_ID1 in 'Source\SN4A\Failed_Cartons_Input_ID1.pas' {Failed_Cartons_Input_ID},
  Failed_Cartons_Input1 in 'Source\SN4A\Failed_Cartons_Input1.pas' {Failed_Cartons_Input},
  InventoryBC_Print1 in 'Source\SN35\InventoryBC_Print1.pas' {InventoryBC_Print},
  NguyenLieuDauVaoTN in 'Source\SN9\NguyenLieuDauVaoTN.pas' {IncomingMatTest},
  DailyOutsourcingCheck_ in 'Source\SN9\DailyOutsourcingCheck_.pas' {DailyOutsourcingCheck},
  IncomeMatRubberOutsole in 'Source\SN9\IncomeMatRubberOutsole.pas' {IncomeMatRubberOutsoles},
  IncomeMatMidInSoles in 'Source\SN9\IncomeMatMidInSoles.pas' {IncomeMatMidInSole},
  IncomeMatEvaPaintings in 'Source\SN9\IncomeMatEvaPaintings.pas' {IncomeMatEvaPainting},
  ProduceMatFailure in 'Source\SN9\ProduceMatFailure.pas' {ProducMatFailure},
  IncomeUpperMaterials in 'Source\SN9\IncomeUpperMaterials.pas' {IncomeUpperMaterial};

{$R *.res}

var
  MutexHandle: THandle;
begin
  MutexHandle := Windows.CreateMutex(Nil, true, 'QC.exe');
  if (Mutexhandle <> 0) then
  begin
    if (GetLastError = Windows.ERROR_ALREADY_EXISTS) then
    begin
      CloseHandle(MutexHandle);
      Halt;
    end;
  end;

  Application.Initialize;
  login := Tlogin.Create(Application);
  login.Show;
  login.Update;
  //Application.CreateForm(TLOGIN, LOGIN);
  Application.Title := 'Lai Yih ERP system----QC';
  Application.CreateForm(TDM2, DM2);
  Application.CreateForm(Tmain, main);
  QCFlowChart := TQCFlowChart.Create(main);
  login.Hide;
  login.Free;
  Application.Run;
end.
